(define (problem miconic3x2)
	(:domain miconic)
	(:objects floor1 floor2 floor3 floor4 person1)
	(:init (above floor1 floor2)
		(above floor2 floor3)
		(above floor3 floor4)
		(lift_pos floor1)
		(floor floor1)
		(floor floor2)
		(floor floor3)
		(floor floor4)
		(person person1)
		(in_lift person1))
	(:goal (and (in_floor person1 floor2))))
