(define (problem blocksworld-6)
 (:domain blocksworld)
 (:objects b1 b2 b3 b4 b5 b6 - object)
 (:init 
    (clear b1)
    (clear b2)
    (clear b3)
    (clear b4)
    (clear b5)
    (clear b6)
    (on-table b1)
    (on-table b2)
    (on-table b3)
    (on-table b4)
    (on-table b5)
    (on-table b6)
    (eq b1 b1)
    (eq b2 b2)
    (eq b3 b3)
    (eq b4 b4)
    (eq b5 b5)
    (eq b6 b6))
 (:goal  (and)))
