(define (problem blocksworld-354)
 (:domain blocksworld)
 (:objects b1 b2 b3 - object)
 (:init 
    (clear b1)
    (clear b2)
    (clear b3)
    (on-table b1)
    (on-table b2)
    (on-table b3)
    (eq b1 b1)
    (eq b2 b2)
    (eq b3 b3))
 (:goal  (and)))
