(define (problem friendsandrivals4)
 (:domain friendsandrivals)
 (:objects b1 b2 b3 b4)
 (:init 
    (has_no_rival b1)
    (has_no_rival b2)
    (has_no_rival b3)
    (has_no_rival b4)
    (has_no_friend b1)
    (has_no_friend b2)
    (has_no_friend b3)
    (has_no_friend b4)
    (eq b1 b1)
    (eq b2 b2)
    (eq b3 b3)
    (eq b4 b4))
 (:goal  (and)))