
(define (domain hanoi)
(:requirements :negative-preconditions :equality :strips)
(:predicates (clear ?x)
             (on ?x ?y)
             (smaller ?x ?y))

(:action move
:parameters (?disc ?from ?to)
:precondition (and (smaller ?disc ?from) 
                   (smaller ?disc ?to) 
                   (on ?disc ?from) 
                   (clear ?disc) 
                   (clear ?to)
                   (not (= ?from ?to))
                   (not (= ?disc ?to))
                   (not (= ?from ?disc)))
:effect  (and (clear ?from) 
              (on ?disc ?to) 
              (not (on ?disc ?from))  
              (not (clear ?to)))
 )) 
