(define (problem gripper-3)
(:domain gripper-strips)
(:objects  left right middle middle2 ball1 ball2 ball3 ball4 ball5 ball6 rooma roomb)
(:init
(room rooma)
(room roomb)
(gripper left)
(gripper right)
(gripper middle)
(gripper middle2)
(ball ball1)
(ball ball2)
(ball ball3)
(ball ball4)
(ball ball5)
(ball ball6)
(free left)
(free right)
(free middle)
(free middle2)
(at ball1 rooma)
(at ball2 rooma)
(at ball3 rooma)
(at ball4 roomb)
(at ball5 roomb)
(at ball6 rooma)
(at-robby rooma)
(eq rooma rooma)
(eq roomb roomb)
)
(:goal
(and
(at ball1 roomb)
(at ball2 roomb)
(at ball3 roomb)
)
)
)
