(define (problem gripper-3-2)
(:domain gripper-strips)
(:objects  left right ball1 ball2 rooma roomb roomc)
(:init
(room rooma)
(room roomb)
(room roomc)
(gripper left)
(gripper right)
(ball ball1)
(ball ball2)
(free left)
(free right)
(at ball1 rooma)
(at ball2 rooma)
(at-robby rooma)
(eq rooma rooma)
(eq roomb roomb)
(eq roomc roomc)
)
(:goal
(and
(at ball1 roomb)
(at ball2 roomb)
)
)
)
