(define (problem BLOCKS-5-0)
(:domain BLOCKS)
(:objects E D B A C F G - block)
(:init  (clear A)
        (clear B) 
        (clear C) 
        (clear D) 
        (clear E)
        (clear F)
        (clear G)
        (ontable A) 
        (ontable B) 
        (ontable C) 
        (ontable D) 
        (ontable E)
        (ontable F)
        (ontable G)
        (HANDEMPTY))
(:goal (and (on E D) (on D C) (on C B) (on B A)))
)
