(define (problem BLOCKS-5-0)
(:domain BLOCKS)
(:objects E D B A C - block)
(:init  (clear A)
        (clear B) 
        (clear C) 
        (clear D) 
        (clear E) 
        (ontable A) 
        (ontable B) 
        (ontable C) 
        (ontable D) 
        (ontable E) 
        (HANDEMPTY))
(:goal (and (on E D) (on D C) (on C B) (on B A)))
)
