(define (domain xyz)
(:requirements :negative-preconditions)

(:predicates 
	(clear ?x0 ?x1)
	(smaller ?x0 ?x1)
	(on ?x0 ?x1)
	(handempty ?x0 ?x1)
	(holding ?x0 ?x1)
	(handfull ?x0 ?x1)
)

(:action stack
 :parameters (?x0 ?x1 ?x2) 
 :precondition (and 
				 (clear ?x1 ?x1)
				 (smaller ?x0 ?x1)
				 (holding ?x0 ?x0)
				 (handfull ?x2 ?x2)
			(not (clear ?x0 ?x1))
			(not (clear ?x1 ?x2))
			(not (clear ?x2 ?x1))
			(not (clear ?x0 ?x0))
			(not (clear ?x2 ?x0))
			(not (clear ?x0 ?x2))
			(not (clear ?x2 ?x2))
			(not (clear ?x1 ?x0))
			(not (smaller ?x1 ?x2))
			(not (smaller ?x2 ?x1))
			(not (smaller ?x0 ?x0))
			(not (smaller ?x1 ?x1))
			(not (smaller ?x2 ?x0))
			(not (smaller ?x0 ?x2))
			(not (smaller ?x2 ?x2))
			(not (smaller ?x1 ?x0))
			(not (on ?x0 ?x1))
			(not (on ?x1 ?x2))
			(not (on ?x2 ?x1))
			(not (on ?x0 ?x0))
			(not (on ?x1 ?x1))
			(not (on ?x2 ?x0))
			(not (on ?x0 ?x2))
			(not (on ?x2 ?x2))
			(not (on ?x1 ?x0))
			(not (handempty ?x0 ?x1))
			(not (handempty ?x1 ?x2))
			(not (handempty ?x2 ?x1))
			(not (handempty ?x0 ?x0))
			(not (handempty ?x1 ?x1))
			(not (handempty ?x2 ?x0))
			(not (handempty ?x0 ?x2))
			(not (handempty ?x2 ?x2))
			(not (handempty ?x1 ?x0))
			(not (holding ?x0 ?x1))
			(not (holding ?x1 ?x2))
			(not (holding ?x2 ?x1))
			(not (holding ?x1 ?x1))
			(not (holding ?x2 ?x0))
			(not (holding ?x0 ?x2))
			(not (holding ?x2 ?x2))
			(not (holding ?x1 ?x0))
			(not (handfull ?x0 ?x1))
			(not (handfull ?x1 ?x2))
			(not (handfull ?x2 ?x1))
			(not (handfull ?x0 ?x0))
			(not (handfull ?x1 ?x1))
			(not (handfull ?x2 ?x0))
			(not (handfull ?x0 ?x2))
			(not (handfull ?x1 ?x0)))
 :effect (and 
			(not (clear ?x1 ?x1))
			(not (holding ?x0 ?x0))
			(not (handfull ?x2 ?x2))
				 (clear ?x0 ?x0)
				 (on ?x0 ?x1)
				 (handempty ?x2 ?x2)
		  )
)

(:action unstack
 :parameters (?x0 ?x1 ?x2) 
 :precondition (and 
				 (clear ?x0 ?x0)
				 (smaller ?x0 ?x2)
				 (on ?x0 ?x2)
				 (handempty ?x1 ?x1)
			(not (clear ?x0 ?x1))
			(not (clear ?x1 ?x2))
			(not (clear ?x2 ?x1))
			(not (clear ?x1 ?x1))
			(not (clear ?x2 ?x0))
			(not (clear ?x0 ?x2))
			(not (clear ?x2 ?x2))
			(not (clear ?x1 ?x0))
			(not (smaller ?x0 ?x1))
			(not (smaller ?x1 ?x2))
			(not (smaller ?x2 ?x1))
			(not (smaller ?x0 ?x0))
			(not (smaller ?x1 ?x1))
			(not (smaller ?x2 ?x0))
			(not (smaller ?x2 ?x2))
			(not (smaller ?x1 ?x0))
			(not (on ?x0 ?x1))
			(not (on ?x1 ?x2))
			(not (on ?x2 ?x1))
			(not (on ?x0 ?x0))
			(not (on ?x1 ?x1))
			(not (on ?x2 ?x0))
			(not (on ?x2 ?x2))
			(not (on ?x1 ?x0))
			(not (handempty ?x0 ?x1))
			(not (handempty ?x1 ?x2))
			(not (handempty ?x2 ?x1))
			(not (handempty ?x0 ?x0))
			(not (handempty ?x2 ?x0))
			(not (handempty ?x0 ?x2))
			(not (handempty ?x2 ?x2))
			(not (handempty ?x1 ?x0))
			(not (holding ?x0 ?x1))
			(not (holding ?x1 ?x2))
			(not (holding ?x2 ?x1))
			(not (holding ?x0 ?x0))
			(not (holding ?x1 ?x1))
			(not (holding ?x2 ?x0))
			(not (holding ?x0 ?x2))
			(not (holding ?x2 ?x2))
			(not (holding ?x1 ?x0))
			(not (handfull ?x0 ?x1))
			(not (handfull ?x1 ?x2))
			(not (handfull ?x2 ?x1))
			(not (handfull ?x0 ?x0))
			(not (handfull ?x1 ?x1))
			(not (handfull ?x2 ?x0))
			(not (handfull ?x0 ?x2))
			(not (handfull ?x2 ?x2))
			(not (handfull ?x1 ?x0)))
 :effect (and 
			(not (clear ?x0 ?x0))
			(not (on ?x0 ?x2))
			(not (handempty ?x1 ?x1))
				 (clear ?x2 ?x2)
				 (holding ?x0 ?x0)
				 (handfull ?x1 ?x1)
		  )
)

)