(define (domain switches)
(:requirements :negative-preconditions :equality :strips)
(:predicates (sw1 ?x)
             (sw2 ?x)
             (sw3 ?x)
             (sw4 ?x)
             (sw5 ?x)
             (sw6 ?x)
             (sw7 ?x)
             (sw8 ?x)
             (sw9 ?x)
             (sw10 ?x)
             (sw11 ?x))

(:action turn-on-1
:parameters (?this)
:precondition (and (not (sw1 ?this)))
:effect  (and (sw1 ?this))
 )
(:action turn-off-1
:parameters (?this)
:precondition (and (sw1 ?this) )
:effect  (and (not (sw1 ?this)))
 )
(:action turn-on-2
:parameters (?this)
:precondition (and (sw1 ?this) 
                   (not (sw2 ?this)))
:effect  (and (sw2 ?this))
 )
(:action turn-off-2
:parameters (?this)
:precondition (and (sw2 ?this) 
                   (not (sw1 ?this)))
:effect  (and (not (sw2 ?this)))
 )
(:action turn-on-3
:parameters (?this)
:precondition (and (sw2 ?this) 
                   (not (sw3 ?this)))
:effect  (and (sw3 ?this))
 )
(:action turn-off-3
:parameters (?this)
:precondition (and (sw3 ?this) 
                   (not (sw2 ?this)))
:effect  (and (not (sw3 ?this)))
 )
(:action turn-on-4
:parameters (?this)
:precondition (and (sw3 ?this) 
                   (not (sw4 ?this)))
:effect  (and (sw4 ?this))
 )
(:action turn-off-4
:parameters (?this)
:precondition (and (sw4 ?this) 
                   (not (sw3 ?this)))
:effect  (and (not (sw4 ?this)))
 )
(:action turn-on-5
:parameters (?this)
:precondition (and (sw4 ?this) 
                   (not (sw5 ?this)))
:effect  (and (sw5 ?this))
 )
(:action turn-off-5
:parameters (?this)
:precondition (and (sw5 ?this) 
                   (not (sw4 ?this)))
:effect  (and (not (sw5 ?this)))
 )
(:action turn-on-6
:parameters (?this)
:precondition (and (sw5 ?this) 
                   (not (sw6 ?this)))
:effect  (and (sw6 ?this))
 )
(:action turn-off-6
:parameters (?this)
:precondition (and (sw6 ?this) 
                   (not (sw5 ?this)))
:effect  (and (not (sw6 ?this)))
 )
(:action turn-on-7
:parameters (?this)
:precondition (and (sw6 ?this) 
                   (not (sw7 ?this)))
:effect  (and (sw7 ?this))
 )
(:action turn-off-7
:parameters (?this)
:precondition (and (sw7 ?this) 
                   (not (sw6 ?this)))
:effect  (and (not (sw7 ?this)))
 )
(:action turn-on-8
:parameters (?this)
:precondition (and (sw7 ?this) 
                   (not (sw8 ?this)))
:effect  (and (sw8 ?this))
 )
(:action turn-off-8
:parameters (?this)
:precondition (and (sw8 ?this) 
                   (not (sw7 ?this)))
:effect  (and (not (sw8 ?this)))
 )
(:action turn-on-9
:parameters (?this)
:precondition (and (sw8 ?this) 
                   (not (sw9 ?this)))
:effect  (and (sw9 ?this))
 )
(:action turn-off-9
:parameters (?this)
:precondition (and (sw9 ?this) 
                   (not (sw8 ?this)))
:effect  (and (not (sw9 ?this)))
 )
(:action turn-on-10
:parameters (?this)
:precondition (and (sw9 ?this) 
                   (not (sw10 ?this)))
:effect  (and (sw10 ?this))
 )
(:action turn-off-10
:parameters (?this)
:precondition (and (sw10 ?this) 
                   (not (sw9 ?this)))
:effect  (and (not (sw10 ?this)))
 )
(:action turn-on-11
:parameters (?this)
:precondition (and (sw10 ?this) 
                   (not (sw11 ?this)))
:effect  (and (sw11 ?this))
 )
(:action turn-off-11
:parameters (?this)
:precondition (and (sw11 ?this) 
                   (not (sw10 ?this)))
:effect  (and (not (sw11 ?this)))
 ))
 
